##################
###项目配置文件####
##################

---

#全局配置
env: "develop"
debug: true
http_port: ":5000"

#MYSQL配置
mysql:
  learn:
    host: 127.0.0.1
    port: 3306
    database: learning
    username: wangxin
    password: MD_wangxin3#4$
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 21600

# Log 配置
log:
  logoutput: file             # 日志输出[stdout, stderr, file]
  logpath: "runtime/"         # 日志路径
  logformat: json             # 日志格式化类型 [json, text]
  max_age: 100                # 日志最大保留时长：100天
  hooks:                      # 日志钩子
    dingding:
      enable: false
      url: https://oapi.dingtalk.com/robot/send?access_token=xxxxx
      level: error            # 钉钉告警日志级别 [debug, info, error]

# chromedriver 配置
chrome:
  port: 9090
